PG_HOST = "ep-soft-scene-anfryyt3-pooler.c-6.us-east-1.aws.neon.tech"
PG_PORT = "5432"
PG_DB = "neondb"
PG_USER = "neondb_owner"
PG_PASSWORD = "npg_TCRprGVP8b6Y"
GOOGLE_API_KEY = "your_google_api_key"
SESSION_TTL_HOURS = "24"
RESET_TTL_MINUTES = "30"